package:
  name: kodoja
  version: "0.0.0"

source:
  fn: v0.0.0.tar.gz
  url: https://github.com/abaizan/kodoja/archive/fc423ef1edc6eabe2fcde25acea6799009ecdc03.tar.gz
  sha256: b196eda8cea1e680eee7c25766701435ea965b0936c7bb557121f52f5a878a1a

build:
  number: 0

requirements:
  run:
    - python
    - kraken
    - kaiju
    - fastqc
    - trimmomatic

test:
  commands:
    - diagnostic_master.py -h

about:
  home: https://github.com/abaizan/kodoja/
  license: MIT
  summary: Kodoja: identifying viruses from plant RNA sequencing data 
