package:
  name: kodoja
  version: "0.0.1"

source:
  url: https://github.com/abaizan/kodoja/archive/kodoja-v0.0.1.tar.gz
  sha256: b67f20251928382a17f6f918a40e6287ab392ff294d6ae24c2af8ea686c6b31a

build:
  number: 0

requirements:
  run:
    - python
    - kraken
    - kaiju
    - fastqc
    - trimmomatic
    - numpy
    - pandas
    - biopython
    - ncbi-genome-download

test:
  commands:
    - kodoja_search.py --version
    - kodoja_build.py --version
    - kodoja_retrieve.py --version

about:
  home: https://github.com/abaizan/kodoja/
  license: MIT
  summary: "Kodoja: identifying viruses from plant RNA sequencing data"
